#pragma once

using namespace ATL;

template <class T>
class CProxy_ISvcVersionEvents : public IConnectionPointImpl<T, &__uuidof( _ISvcVersionEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
